### PR TITLE
zephyr: remove building for intel_bdw_adsp and intel_byt_adsp

### PR DESCRIPTION
**Pull request by dcpleung**
These platforms will be removed from the Zephyr SDK as they are not being used in the main Zephyr repo. So remove the references to build the library for them.

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Comment by dcpleung** [comment]
This needs to be merged before https://github.com/zephyrproject-rtos/sdk-ng/pull/579 when building for the new SDK.

**Comment by stephanosio** [comment]
We do not run GitHub Actions in the Zephyr fork of the picolibc.

This patch should be submitted to the upstream picolibc repository:
https://github.com/picolibc/picolibc

**Comment by dcpleung** [comment]
haha... I thought these were Zephyr add-ons in the fork. I will re-submit upstream.

**Comment by dcpleung** [comment]
Use this instead: https://github.com/picolibc/picolibc/pull/391

**Pull request closed without merging**
